### ISSUE TITLE
Implement recipe scheduler

### ISSUE THREAD

**Issue by kkaarreell** [RedHatQE/newa#11]
Test scheduler is responsible for deriving all the parameters necessary for the actual test execution.
On the input it would read YAML config produced by Jira processor, beside the associated Jira issue it should contain information about the "Test job recipe". This is currently not defined formally, we have just a POC implementation for the past.
What the test processor / scheduler would do is:

- parse recipe configuration from the specified YAML file
- generate or valid environment combinations
- for each valid combinarion generate YAML file as an input for test executor that is (later) responsible for executing the actual test job

Workflow is also briefly captured in https://miro.com/app/board/uXjVN67jOho=/

Example of a recipe file:
```
environment:
  COMPOSE: RHEL-9.4.0-Nightly
context:
  distro: $COMPOSE
dimensions:
  arch:
    - environment:
        ARCH: x86_64
      context:
        arch: x86_64
    - environment:
        ARCH: s390x
      context:
        arch: s390x
  slot:
    - environment:
        SLOT: 1
      when: $ARCH == s390x
    - environment:
        SLOT: 3

plan:
  name: /demodata/plan/opencryptoki
  git-url: https://path/to/test/repository.git
  git-ref: main

execute:
  how: testing-farm
  extra_params: "--arch $ARCH  --compose $COMPOSE"

```

One of the produced YAML file for the executor should roughly look like:
```
event:
  ...

errata:
  ...

jira:
   ...

execute:
  how: testing-farm
  context:
     distro: RHEL-9.4.0-Nightly
     arch: s390x
  environment:
    SLOT: 1
    ARCH: s390x
  plan: /demodata/plan/opencryptoki
  git-url: https://path/to/test/repository.git
  git-ref: main
```

Of course, any of the above could be subject of a change, depending on the actual needs and newa code.
