### ISSUE TITLE
Ability to uniquely identify current and obsoleted Jira issue matching the respective item from Jira configuration

### ISSUE THREAD

**Issue by kkaarreell** [RedHatQE/newa#14]
Let's suppose we have the following config item in the Jira processor configuration:
```
issues:
 - summary: "Testing ER#{errata.id} {errata.summary}"
   type: epic
   id: errata_epic
   on_respin: keep
-  summary: "Errata testing respin {errata.respin_count}"
   type: task
   id: errata_task
   parent: errata_epic
   on_respin: close
```
Now let's say we want to perform steps suggested by the configuration above for a respun advisory, in particular:
1. Search in Jira for epic to double-check if it already exists and create it if it does not
2. Search in Jira for the task so that it can be closed and create a new task.
The problem we are facing is: How to uniquely identify those new and obsoleted Jira issues so we can find them?
