### ISSUE TITLE
Recipe file structure needs improvements

### ISSUE THREAD

**Issue by kkaarreell** [RedHatQE/newa#35]
There are things we should improve in the current recipe file structure. The current demo looks like this:
```
fixtures:
  environment:
    PLANET: Earth

  git_url: https://github.com/RedHatQE/newa.git
  git_ref: main
  tmt_path: demodata
  plan: /plan1

dimensions:
  cities:
    - environment:
        CITY: Brno
    - environment:
        CITY: Boston
      when: CONTEXT.color is match("blue")
  colors:
    - context:
        color: red
      when: ENVIRONMENT.CITY is not match("Brno")
    - context:
        color: blue
```
Suggestions for improvements:
 - Q1: Keep testingfarm, tmt, reportportal under fixtures or have it standalone? 
 - Q2: Use even more levels?

Now discuss those individual questions in detail:

Q1: Keep testingfarm, tmt, reportportal under fixtures or have it standalone? 
Having it under fixtures would simplify operating with this settings within dimensions as well. But is it necessary?
Having it separatele and utilize Jinja template rendering for parametrization might be sufficient and be more user friendly.

Example:
```
dimensions:
  architecture:
    - context:
        arch: x86_64
    - context:
        arch: s390x

testingfarm:
  cli_args: "{{ --arch CONTEXT.arch }}"
reportportal:
  launch_attributes:
    arch: "{{ CONTEXT.arch }}"
```

However, with may do the same under fixtures as well and a user may use it e.g. to extend launch attributes.

Example:
```
fixtures:
  reportportal:
    launch_attributes:
      arch: "{{ CONTEXT.arch }}"

dimensions:
  architecture:
    - context:
        arch: x86_64
    - context:
        arch: s390x
  fips:
    - context:
        fips: yes
      reportportal:
        launch_attributes:
          fips: yes
    - context:
        fips: no
```

Q2: Use even more levels?
The advantage might be better control in case we are going to implement support e.g. for TF direct requests through API. Also, we would avoid repeating prefixes like "launch_" or "cli_" etc.

Example:
```
testingfarm:
  cli:
    args:
reportportal:
  launch:
    description:
    name:
    attributes:
```
